FROM java:8-jre
WORKDIR usr/src
Add ./target/moviejpa-0.0.1-SNAPSHOT.jar usr/src/moviejpa-0.0.1-SNAPSHOT.jar
ENV MYSQL_ROOT_PASSWORD=pass
ENV MYSQL_MYURL=jdbc:mysql://localhost:3306/ibmnew?createDatabaseIfNotExist=true&user=root&password=pass
ENTRYPOINT ["java","-jar","moviejpa-0.0.1-SNAPSHOT.jar"]